/**********************************************************************************************************************
 * \file Asclin.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <string.h>
#include <stdint.h>
#include "TimeMeasure.h"
#include "ASCLIN.h"
#include "IfxAsclin_Asc.h"
#include "IfxAsclin_PinMap.h"
#include "Bsp.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ASC_MODULE   MODULE_ASCLIN1
#define ASC_PIN_TX   IfxAsclin1_TX_P15_0_OUT  //mikro BUS의 USB-UART 핀
#define ASC_PIN_RX   IfxAsclin1_RXA_P15_1_IN
// + IfxAsclin0_TX_P14_0_OUT, IfxAsclin0_RXA_P14_1_IN  온보드 통신 핀

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
int trans_split = 0;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
IfxAsclin_Asc g_asc;

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void initAsclin(void){
    IfxAsclin_Asc_Config ascConfig;
    const IfxAsclin_Asc_Pins ascPins = {
        .cts      = NULL_PTR,
        .ctsMode  = IfxPort_InputMode_pullUp,
        .rx       = &ASC_PIN_RX,
        .rxMode   = IfxPort_InputMode_pullUp,
        .rts      = NULL_PTR,
        .rtsMode  = IfxPort_OutputMode_pushPull,
        .tx       = &ASC_PIN_TX,
        .txMode   = IfxPort_OutputMode_pushPull,
        .pinDriver= IfxPort_PadDriver_cmosAutomotiveSpeed1
    };

    IfxAsclin_Asc_initModuleConfig(&ascConfig, &ASC_MODULE);

    /* 1,000,000 baud, 8N1 */
    ascConfig.baudrate.baudrate     = 2000000;
    ascConfig.pins = &ascPins;

    IfxAsclin_Asc_initModule(&g_asc, &ascConfig);
}

/* SIMPLE_UART_TRANSMIT에 대응 */
void ascTransmit(const uint8_t *pData, uint16_t size, Ifx_TickTime timeout)
{
    START_TICK_MANAGER(AscTransmit_Time);

    /* if (huart->gState == HAL_UART_STATE_READY) 대응 */
    if (g_asc.txInProgress == FALSE)
    {
        Ifx_TickTime deadLine = getDeadLine(timeout);

        /* todo: 폴링 방식으로 인한 무한 대기 및 오버런 문제 발생 가능성 있으므로 수정 필요 */
        while (((uint16_t)IfxAsclin_getTxFifoFillLevel(&ASC_MODULE) + size) > ASC_TX_FIFO_SIZE)
        {
            if (isDeadLine(deadLine))
            {
                END_TICK_MANAGER(AscTransmit_Time);
                return;
            }
        }
        for (uint16_t idx = 0u; idx < size; idx++)
        {
                IfxAsclin_writeTxData(&ASC_MODULE, pData[idx]);
        }
    }

    END_TICK_MANAGER(AscTransmit_Time);
}

/* 데이터 전송 - STM32 data_trans()와 동일 */
void dataTrans(float dataIn[2])
{
    START_TICK_MANAGER(DataTrans_Time);

    uint8_t temp[4];
    uint8_t idxChecker;

    /* 프레임,세트 End Checker */
    uint8_t END_CHECKER     = 0x55;  // 0b01010101
    uint8_t SET_END_CHECKER = 0x33;  // 0b00110011

    static int i = 0;


    i = 0;
    memcpy(temp, &dataIn[i], 4);
    idxChecker = (uint8_t)i;
    ascTransmit(&idxChecker, 1, TIME_INFINITE);
    ascTransmit(temp, 4, TIME_INFINITE);
    ascTransmit(&END_CHECKER, 1, TIME_INFINITE);

    i = 1;
    memcpy(temp, &dataIn[i], 4);
    idxChecker = (uint8_t)i;
    ascTransmit(&idxChecker, 1, TIME_INFINITE);
    ascTransmit(temp, 4, TIME_INFINITE);
    ascTransmit(&END_CHECKER, 1, TIME_INFINITE);

    ascTransmit(&SET_END_CHECKER, 1, TIME_INFINITE);


    END_TICK_MANAGER(DataTrans_Time);
}



