/**********************************************************************************************************************
 * \file CCU6_Interrupt.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "TimeMeasure.h"
#include "CCU6_Interrupt.h"
#include "IfxCcu6.h"
#include "IfxCpu_Irq.h"
#include "CCU6_Config.h"
#include "ASCLIN.h"

//#include "nn_basic.h"
//#include "nn_basic_diag.h"
//#include "nn_MTPA.h"
#include "nn_duty_comp.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
volatile uint32 g_isrCounter = 0;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
static float data[4] = {0.f, 0.f, 0.f, 0.f};

/* 통신 주기를 늦추기 위한 counter */
static uint16 ascCounter = 0u;
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
static void updateTestData(void)
{
    START_TICK_MANAGER(UpdateData_Time);

    /* 테스트 데이터 업데이트 함수
     * data[0], [2] : 0 -> 1000 -> 0 으로 반복되는 업-다운 카운터
     * data[1], [3] : data update counter */
    static float   counter = 0.f;
    static float   wave    = 0.f;
    static boolean inc_dec = TRUE;

    counter += 1.f;
    if (counter > 1000) counter = 0.f;

    if (inc_dec)
    {
        wave += 1.f;
        if (wave >= 100.f) inc_dec = FALSE;
    }
    else
    {
        wave -= 1.f;
        if (wave <= 0) inc_dec = TRUE;
    }

    data[0] = wave;
    data[1] = counter;
    data[2] = wave;
    data[3] = counter;

    END_TICK_MANAGER(UpdateData_Time);
}

IFX_INTERRUPT(isrCCU6T12, 0, ISR_PRIORITY_CCU6);
void isrCCU6T12(void)
{
    /* CCU6 인터럽트 주기와 ISR 전체 실행 시간을 측정한다. */
    START_TICK_MANAGER(Control_Time);

    /*
     * ISR 진입 시 T12 인터럽트 플래그를 먼저 해제한다.
     * 실행 중 오버런이 발생하면 현재 ISR 종료 직후 다음 인터럽트를
     * 바로 처리할 수 있다.
     */
    IfxCcu6_clearT12OneNotification(&MODULE_CCU60);

    /* ISR 실행 횟수와 통신 주기 분주용 카운터를 갱신 */
    g_isrCounter++;
    ascCounter++;

    /* UART 송신 시험용 데이터를 갱신 */
    data[0] = 1.1f;
    data[1] = -2.2f;
    /* dataTrans(data); */



    /*
    * MTPA 신경망 추론 시험
    * 단일 토크 지령을 입력하여 MTPA 전류 지령을 계산한다.
    */
    /*
    volatile float temp_input = 100.f;
    NN_Run(&temp_input);
    */

    /*
    * 컨버터 듀티 보상
    */
    volatile float temp_input[NN_INPUT_NUM] = {8.f , 2.f};
    NN_Run(&temp_input[0]);


    /*
    * 고장 진단 신경망 시험 입력
    * 검증용 CSV 파일의 102행(Fault ID 3) 샘플
    *
    * 고장 진단 모델을 사용할 때만 아래 블록을 활성화하고,
    * 위의 MTPA 시험 코드는 동시에 비활성화함
    */
    /*
    volatile float temp_input[NN_INPUT_NUM] =   {
        5.4148f, -2.0793f,  -4.1294f, -4.1294f,   8.8633f, 10.8036f,
        -0.1978f, -0.1354f,  -9.4121f, -9.4121f, -11.9553f, -2.2192f,
        -5.3062f,  2.2049f,  13.1828f, 13.1828f,   2.9556f, -8.8627f
    };
    NN_Run(&temp_input[0]);
    */

    /* 현재 ISR의 실행 시간 측정을 종료한다. */
    END_TICK_MANAGER(Control_Time);
}




