/**********************************************************************************************************************
 * \file CCU6_Config.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "CCU6_Config.h"

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
IfxCcu6_TimerWithTrigger g_ccu6Timer;

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void initCcu6(void)
{
    /* T12 타이머 설정 */
    IfxCcu6_TimerWithTrigger_Config timerConfig;
    IfxCcu6_TimerWithTrigger_initConfig(&timerConfig, &MODULE_CCU60);

    timerConfig.base.frequency        = CCU6_FREQ_HZ;
    timerConfig.base.countDir         = IfxCcu6_Timer_CountDir_upAndDown;   // center-aligned 모드로 카운팅
    timerConfig.base.isrPriority      = ISR_PRIORITY_CCU6;
    /* (isrPriority > 0) 이면 IfxCcu6_TimerWithTrigger_init 내의
     * IfxCcu6_TimerWithTrigger_initInterrupt에서 인터럽트 자동 활성화
     * + center-aligned 모드이면 oneMatch 인터럽트로 기본 설정 */


    /* T13을 추가 트리거용으로 사용 시
    timerConfig.base.trigger.enabled       = TRUE;  // T13 트리거 사용
    timerConfig.base.trigger.outputEnabled = FALSE; // 외부 핀으로 출력은 안함
    */

    IfxCcu6_TimerWithTrigger_init(&g_ccu6Timer, &timerConfig);

    /* 모든 설정이 끝난 뒤 T12 시작 */
    IfxCcu6_TimerWithTrigger_run(&g_ccu6Timer);
}
