/**********************************************************************************************************************
 * \file StmTimeMeasure.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef TIMEMEASURE_H_
#define TIMEMEASURE_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxStm.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define CLOCK_HZ    (100.0f * 1.0e6f)

#define TICK_TO_NS      (1.0e9f / CLOCK_HZ)
#define TICK_TO_US      (1.0e6f / CLOCK_HZ)



#define GET_TICK()                                             \
    IfxStm_getLower(&MODULE_STM0)


#define CALC_PERIOD(x)                                             \
    do                                                             \
    {                                                              \
        (x).period_us =                                            \
            (float32)(GET_TICK() - (x).tickStart)              \
            * TICK_TO_US;                                          \
    } while (0)


#define TICK_START(x)                                              \
    do                                                             \
    {                                                         (x).tickStart = GET_TICK();                            \
    } while (0)


#define START_TICK_MANAGER(x)                              \
    do                                                     \
    {                                                      \
        if ((x).cnt > 0u)                                  \
        {                                                  \
            CALC_PERIOD(x);                                \
        }                                                  \
        else                                               \
        {                                                  \
            (x).period_us = 0.0f;                          \
        }                                                  \
                                                           \
        TICK_START(x);                                     \
        (x).cnt++;                                         \
    } while (0)


#define TICK_STOP_CHECK(x)                                         \
    do                                                             \
    {                                                              \
        (x).elapsedTime_us =                                       \
            (float32)(GET_TICK() - (x).tickStart)              \
            * TICK_TO_US;                                          \
    } while (0)


#define TICK_MAX_CHECK(x)                                          \
    do                                                             \
    {                                                              \
        if ((x).elapsedTime_us > (x).maxElapsedTime_us)            \
        {                                                          \
            (x).maxElapsedTime_us = (x).elapsedTime_us;            \
        }                                                          \
    } while (0)


#define PERIOD_MAX_CHECK(x)                                        \
    do                                                             \
    {                                                              \
        if ((x).period_us > (x).maxPeriod_us)                       \
        {                                                          \
            (x).maxPeriod_us = (x).period_us;                       \
        }                                                          \
    } while (0)


#define END_TICK_MANAGER(x)                                        \
    do                                                             \
    {                                                              \
        TICK_STOP_CHECK(x);                                        \
        TICK_MAX_CHECK(x);                                         \
        PERIOD_MAX_CHECK(x);                                       \
    } while (0)

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
typedef struct
{
    uint32 cnt;
    uint32 tickStart;

    volatile float32 elapsedTime_us;
    volatile float32 maxElapsedTime_us;
    volatile float32 period_us;
    volatile float32 maxPeriod_us;

} TimeManager;

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* 함수별 측정 변수 */
extern TimeManager Control_Time;
extern TimeManager UpdateData_Time;
extern TimeManager DataTrans_Time;
extern TimeManager AscTransmit_Time;

extern TimeManager NN_Time1;
extern TimeManager NN_Time2;
extern TimeManager NN_Time3;
extern TimeManager NN_Time4;
extern TimeManager NN_Time5;
extern TimeManager NN_Time6;
extern TimeManager NN_Time7;
extern TimeManager NN_Time8;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

#endif /* TIMEMEASURE_H_ */
